{
 "title": "Github stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(github_repo_stats{stat=\"forks_count\"},user)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(github_repo_stats{stat=\"forks_count\", user=\"$user\"},project)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Exporter statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ratelimit limit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_exporter_stats{user=\"$user\",stat=\"ratelimit-limit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratelimit remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_exporter_stats{user=\"$user\",stat=\"ratelimit-remaining\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "User level stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Clones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(github_clones{user=\"$user\",unique=\"false\",project=~\"$project\"}) by (project)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(github_views{user=\"$user\",unique=\"false\"}) by (project)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Open issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(github_repo_stats{user=\"$user\",stat=\"open_issues\",project=~\"$project\"}) by (project)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Open pull requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum(github_repo_stats{user=\"$user\",stat=\"open_pull_requests\",project=~\"$project\"}) by (project)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "#Commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "sum(github_repo_stats{user=\"$user\",stat=\"commits\",project=~\"$project\"}) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Repo stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Branches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"branches\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"tags\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"commits\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contributors",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "github_repo_stats{project=~\"$project\",stat=\"contributors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Open issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"open_issues\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closed issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"closed_issues\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unassigned issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"unassigned_issues\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pull requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Open pull requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"open_pull_requests\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closed pull requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"closed_pull_requests\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unassigned pull requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"unassigned_pull_requests\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true
  },
  {
   "title": "Watchers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"watchers_count\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stargazers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"stargazers_count\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"forks_count\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_stats{project=~\"$project\",stat=\"subscribers_count\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}